version: "3.7"

services:
  web:
    build: ./frontend
    ports:
      - 8501:8501
    volumes:
      - ./frontend:/app/frontend

  api:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
